version: '3.3'
services:
  fluentd:
    image: ${USER_NAME}/fluentd
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    networks:
      back-net:
        aliases:
        - fluentd

  elasticsearch:
    image: elasticsearch:6.4.2
    expose:
      - 9200
    ports:
      - "9200:9200"
    tty : true
    networks:
      back-net:
        aliases:
        - elasticsearch

  kibana:
    image: kibana:6.4.2
    ports:
      - "5601:5601"
    networks:
      back-net:
        aliases:
        - kibana

  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    networks:
      back-net:
        aliases:
        - zipkin
      front-net:
        aliases:
        - zipkin

networks:
  back-net:
    driver: bridge
    ipam:
     config:
     - subnet: 10.0.2.0/24
  front-net:
    driver: bridge
    ipam:
     config:
     - subnet: 10.0.1.0/24
