version: '3.3'
services:
  post_db:
    image: mongo:${MONGO_VER}
    environment:
    - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    volumes:
      - post_db:/data/db
    networks:
      back-net:
        aliases:
        - post_db
        - comment_db
  ui:
    image: ${USER_NAME}/ui:${UI_VER}
    environment:
    - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    ports:
      - ${UI_HOSTPORT}:${UI_CONTAINERPORT}/tcp
    networks:
      front-net:
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.ui

  post:
    image: ${USER_NAME}/post:${POST_VER}
    environment:
    - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    networks:
      back-net:
        aliases:
        - post
      front-net:
        aliases:
        - post
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.post

  comment:
    image: ${USER_NAME}/comment:${COMMENT_VER}
    environment:
    - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    networks:
      back-net:
        aliases:
        - comment
      front-net:
        aliases:
        - comment

volumes:
  post_db:

networks:
  back-net:
    driver: bridge
    ipam:
     config:
     - subnet: 10.0.2.0/24
  front-net:
    driver: bridge
    ipam:
     config:
     - subnet: 10.0.1.0/24
